image: python:3.9.17-slim-bullseye

stages:
  - docs
  
docs:
  stage: docs
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
    - if: $CI_PIPELINE_SOURCE  == "push"
  before_script:
    - apt-get update -y && apt-get install git -y
  script:
    - git config --global user.email "ci@quirkstudios.xyz"
    - git config --global user.name "CI"
    - pip install mkdocs
    - git remote remove origin
    - git remote add origin https://redstoneguy129:$GITLAB_TOKEN@gitlab.com/quirk-studios/quirkcraft/api.git
    - python -m mkdocs gh-deploy