site_name: Quirkcraft
site_url: https://quirkcraft.quirkstudios.xyz
theme:
  name: readthedocs
  custom_dir: theme
nav:
  - Home: 'index.md'
  - Getting Started:
      - Introduction: 'gettingstarted/index.md'
  - Addon:
      - Introduction: 'addon/index.md'
  - Plugin:
      - Introduction: 'plugin/index.md'