site_name: Quirkcraft
site_url: https://quirkcraft.quirkstudios.xyz
theme:
  name: forge
  custom_dir: theme
nav:
  - Home: 'index.md'
  - Getting Started:
    - Introduction: 'gettingstarted/index.md'